# http://module-build.sourceforge.net/META-spec.html
name:         Apache2-ModProxyPerlHtml
version:      4.1
version_from: ModProxyPerlHtml.pm
installdirs:  site
requires:
    IO::Uncompress::AnyInflate
    IO::Compress::Deflate
    IO::Compress::Gzip

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
